### ISSUE TITLE
How can i determine the mutant items?

### ISSUE THREAD

**Issue by Stella1230** [garghub/TROVON#2]
I want to reproduce this paper, but there are some problems with the java code.   How can i determine the mutant items and then i can get the lhs or rhs files to train the seq2seq model?

**Comment by garghub** [comment]
Sorry, I did not understand your question. 
I can definitely try to help you out if you can please elaborate and if possible point to the code where you are having problems.

**Comment by garghub** [comment]
Please do not hesitate to reopen it, if this concerns you. I am closing it because I haven't gotten a response from the issue creator.
